### ISSUE TITLE
Inconsistent example

### ISSUE THREAD

**Issue by itamargiv** [noreading/react-redux-introduction#1]
Hey @noreading 

https://github.com/noreading/react-redux-introduction/blame/master/Readme.md#L287

This example uses stateless component notation "out of the blue" which is a little confusing (especially since there is a chapter below dedicated to it :smile: ) just FYI for the next iteration....

**Comment by itamargiv** [comment]
Great tutorial btw! It really matches up with the breakdown that was made in the curriculum. Thank you for spending the time on it.

**Comment by noreading** [comment]
Hey man! Thx for reporting. :+1: 

This is finally fixed in the new version of the tutorial having the newest npm packages and some other bugs fixed, etc.
